include "States.fbs";
include "Shared.fbs";
include "Sensors.fbs";
include "EKF.fbs";
include "Actuator.fbs";

namespace hprc;

struct BlobCoord {
  index: byte;
  x: byte;
  y: byte;
  width: byte;
  height: byte;
  ellipse_a: byte;
  ellipse_b: byte;
  rotation: int16;
  confidence: float;
}

table PayloadTelemetryPacket {
  shared: Shared;
  state: States = Start;
  sensor_values: Sensors;
  ekf_values: EKF;

  self_righting1_servo: Actuator;
  self_righting2_servo: Actuator;
  latch_servo: Actuator;
  antenna_servo: Actuator;

  motor_left: Actuator;
  motor_right: Actuator;

  blob_data: [BlobCoord];

  horiz_x1: byte;
  horiz_x2: byte;
  horiz_y1: byte;
  horiz_y2: byte;
  horiz_valid: bool;
}

root_type PayloadTelemetryPacket;
