// Sensors.fbs
// Converted from Sensors.capnp

namespace hprc;

struct ASM330Data {
	accel0: float;
	accel1: float;
	accel2: float;
	gyr0: float;
	gyr1: float;
	gyr2: float;
}

struct LSM6Data {
	accel0: float;
	accel1: float;
	accel2: float;
	gyr0: float;
	gyr1: float;
	gyr2: float;
}

struct LIS2MDLData {
	mag0: float;
	mag1: float;
	mag2: float;
}

struct LPS22Data {
	pressure: float;
	temp: float;
}

struct LIV3FData {
	lat: float;
	lon: float;
	alt: float;
	satellites: ubyte;
	epoch_time: uint32;
}

table Sensors {
	asm330: ASM330Data;
	lsm6: LSM6Data;
	lis2mdl: LIS2MDLData;
	lps22: LPS22Data;
	liv3f: LIV3FData;  
}
