// Sensors.fbs
// Converted from Sensors.capnp

namespace hprc;

enum SensorBitfield : ubyte {
	None = 0x00,
	ASM330 = 0x01,
	LSM6 = 0x02,
	LIS2MDL = 0x4,
	LPS22 = 0x8,
	LIV3F = 0x10,
}

struct ASM330Data {
	accel0: float;
	accel1: float;
	accel2: float;
	gyr0: float;
	gyr1: float;
	gyr2: float;
}

struct LSM6Data {
	accel0: float;
	accel1: float;
	accel2: float;
	gyr0: float;
	gyr1: float;
	gyr2: float;
}

struct LIS2MDLData {
	mag0: float;
	mag1: float;
	mag2: float;
}

struct LPS22Data {
	pressure: float;
	temp: float;
}

struct LIV3FData {
	lat: float;
	lon: float;
	alt: float;
	satellites: ubyte;
	epochTime: uint32;
}

table Sensors {
	bitfield: SensorBitfield;
	ASM330: ASM330Data;
	LSM6: LSM6Data;
	LIS2MDL: LIS2MDLData;
	LPS22: LPS22Data;
	LIV3F: LIV3FData;  
}
