// Sensors.fbs
// Converted from Sensors.capnp

namespace hprc;


struct ASM330Data_Accel {
	accel0: float;
	accel1: float;
	accel2: float;
}

struct ASM330Data_Gyro {
	gyr0: float;
	gyr1: float;
	gyr2: float;
}

struct LSM6Data_Accel {
	accel0: float;
	accel1: float;
	accel2: float;
}

struct LSM6Data_Gyro {
	gyr0: float;
	gyr1: float;
	gyr2: float;
}

struct LIS2MDLData {
	mag0: float;
	mag1: float;
	mag2: float;
}

struct LPS22Data {
	pressure: float;
	temp: float;
}

struct LIV3FData {
	lat: float;
	lon: float;
	alt: float;
	satellites: ubyte;
	epochTime: uint32;
}

table Sensors {
  ASM330_accel: ASM330Data_Accel;
  ASM330_gryo: ASM330Data_Gyro;
  LSM6_accel: LSM6Data_Accel;
  LSM6_gyro: LSM6Data_Gyro;
  LIS2MDL: LIS2MDLData;
  LPS22: LPS22Data;
  LIV3F: LIV3FData;  
}